### ISSUE TITLE
Support for 1.12.2

### ISSUE THREAD

**Issue by Rubenicos** [Rosewood-Development/RoseStacker#13]
I loved this plugin, works perfectly in Minecraft 1.16 but as I see the compatible versions are only 1.13 or higher... would be possible to make RoseStacker compatible with a slightly older version such as 1.12.2?
I have multiple servers running Minecraft 1.12.2 (performance reasons) and would like to see RoseStacker on them.

**Comment by Esophose** [comment]
The problem with supporting versions older than 1.13 is that blocks and items use metadata which makes it increasingly difficult to tell different blocks and items with the same IDs apart. The same goes for entities, lots of API was removed and added regarding those to. It's already a bit of a pain just to support 1.13.2 because of API changes. I'll keep this issue open just in case I decide to try adding support for older versions though, I just don't think it will be any time soon.

**Comment by Esophose** [comment]
Closing this, never adding support for anything below 1.13.2, sorry.
